version: '3'
services:
  nest:
    container_name: nest-server
    build:
      context: ./
      dockerfile: ./Dockerfile.dev
    environment:
      - APP_PORT=${APP_PORT}
    ports:
      - "8080:3000"
    volumes:
      - ./:/app